name: Chromatic

# PNPM setup based on https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

on:
  # TODO: Maybe remove the "push" do not re-run the job on the main branch?
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CI: true

concurrency:
  group: chromatic-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TURBO_TELEMETRY_DISABLED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            # Required to calculate chromatic baseline.
            fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
            node-version: ">=24.0.0"
            check-latest: true
            cache: pnpm
            cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Restore Turborepo cache
        id: cache-turborepo-restore
        uses: actions/cache/restore@v4
        with:
          # Using SHA will usually provide cache hit on subsequent commits in a PR
          # but will not provide cache hits between PRs, meaning the first run of a PR
          # will usually only be cache misses.
          key: ${{ runner.os }}-turbo-${{ github.sha }}-chromatic
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.sha }}
            ${{ runner.os }}-turbo-
          path: .turbo

      - name: Get affected Storybooks
        id: affected
        working-directory: ${{ github.workspace }}
        run: pnpm tsx tooling/getAffectedStorybooks.ts
        env:
            PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}

        # -> github.event.pull_request.draft == true || startsWith(github.ref, 'refs/heads/renovate/')

        # Splitting Storybook compilation and Chromatic execution faciliate debugging.
      - name: Build Storybook - Home
        run: pnpm turbo run build-storybook --filter=@apps/home-storybook -- --disable-telemetry --stats-json
        # Must be 'true' not true.
        if: ${{ steps.affected.outputs['@apps/home-storybook'] == 'true' }}

        # Splitting Storybook compilation and Chromatic execution faciliate debugging.
      - name: Build Storybook - Packages
        run: pnpm turbo run build-storybook --filter=@apps/packages-storybook -- --disable-telemetry --stats-json
        # Must be 'true' not true.
        if: ${{ steps.affected.outputs['@apps/packages-storybook'] == 'true' }}

      - name: Chromatic - Home
        uses: chromaui/action@latest
        with:
            projectToken: ${{ secrets.HOME_CHROMATIC_PROJECT_TOKEN }}
            workingDir: apps/home/storybook
            storybookBuildDir: storybook-static
            onlyChanged: true
            exitOnceUploaded: true
            # autoAcceptChanges: 'main'
            # Must be 'false' not false.
            skip: ${{ steps.affected.outputs['@apps/home-storybook'] == 'false' || github.event.pull_request.draft == true || startsWith(github.ref, 'refs/heads/renovate/') }}
            debug: true

      - name: Chromatic - Packages
        uses: chromaui/action@latest
        with:
            projectToken: ${{ secrets.PACKAGES_CHROMATIC_PROJECT_TOKEN }}
            storybookBaseDir: packages/storybook
            storybookBuildDir: packages/storybook/storybook-static
            onlyChanged: true
            exitOnceUploaded: true
            # autoAcceptChanges: 'main'
            # Must be 'false' not false.
            skip: ${{ steps.affected.outputs['@apps/packages-storybook'] == 'false' || github.event.pull_request.draft == true || startsWith(github.ref, 'refs/heads/renovate/') }}
            debug: true

      - name: Save Turborepo cache
        id: cache-turborepo-save
        if: always() && steps.cache-turborepo-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-turborepo-restore.outputs.cache-primary-key }}
          path: .turbo
